# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dba934b1e2480bba384429085ff81b3832d59717b0bb9cd32e85ca1ca19d27c3ad4d1aabdf99bdcc1dfa02d809c47ff24e8d74c4cced0f93ae54834e01915f9

test:
  secret_key_base: 62e92cf008b47625731ebc565dcb86edf31e85170a984047b1b32fb340d038bca8d3027f1641b2191aa9fb88e113d4e1efa7355e22f0dd405de1dc20d37638fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
